# Generated by Django 4.2 on 2023-04-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xithome', '0002_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
