# Generated by Django 4.2 on 2023-04-21 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xithome', '0004_modelname_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True, 'verbose_name': 'user', 'verbose_name_plural': 'user'},
        ),
    ]
