# Generated by Django 4.2 on 2023-04-21 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xithome', '0005_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
